### ISSUE TITLE
Question about preprocessing DNase HiC data

### ISSUE THREAD

**Issue by gitcruz** [esrice/slurm-hic#1]
Hi, 

I am dealing with HiC data produced with the DNase protocol (Ramani et al. 2016, Nature Protocols). I would like to use slurm-hic for this. I've been checking the filter_chimeras.py and combine_ends.py help and (unlike other programs) it seems there is no need to provide the restriction site at all. 

Do the program deals with the data regardless of the digestion protocol? Have you used it with DNase HiC before?

Thanks in advance,
Fernando

**Comment by gitcruz** [comment]
PS. I am concern about the presence of BamHI bridge-adaptor used for proximity ligation.

**Comment by esrice** [comment]
Hi Fernando,

So sorry for the very late reply. Github didn't notify me about this for some reason.

You are correct that those two python scripts do not look for restriction sites. They only use breaks in chimeric alignments to identify ligation junctions in reads rather than the presence of specific sequences, so they should work just fine no matter what enzyme was used.

SALSA2 does ask for a restriction enzyme, but supports `DNASE` as an option instead of a restriction sequence, so you should be able to run this pipeline with DNase by either running the nextflow command with `--enzyme DNASE`, or if running it manually, just substitute `DNASE` for `GATC` in the SALSA command.

Sorry again. Subscribing to this thread to make sure I receive notifications now. Let me know how it went if you tried this already or how it goes if you do in the future.

Ed

**Comment by gitcruz** [comment]
Hi Ed,

This sounds really good. The pre-processing workflow worked really well.

Thanks
Fernando
