### ISSUE TITLE
  Question regarding the use for restriction enzyme digested libraries

### ISSUE THREAD

**Issue by gitcruz** [esrice/slurm-hic#3]
Hi,

I would like to know to which extent the dnase  preprocessing can handle read data coming from a digestion.

I did mapped a library as it was a DNAse library, and then it turned out it was digested with DnpII. Now the genome is scaffolded and curated...not sure if i should redo this.

Do you think specifying the wrong target can affect the mappings and subsequent scaffolding?

Thanks,
F

**Comment by esrice** [comment]
Hi Fernando,

SALSA2 uses the digestion target to do a statistical correction based on the density of these sequences in the various parts of the input. I have never tried to compare results between specifying the correct versus incorrect digest enzyme, so I'm not sure how much it matters.

All that being said, per the README, this pipeline is now deprecated in favor of a much better one, so I strongly recommend using my new one:

https://github.com/WarrenLab/hic-scaffolding-nf

It uses chromap and YAHS instead of bwa and SALSA2, and gets much much better results this way, so do try it out!

Ed

**Comment by gitcruz** [comment]
Hi, 

I've been using YaHS lately and I am quite happy with it. And it doesn't have into account the restriction sites. I'll have a look at your new tool, looks interesting-

My question was more about the preprocessing but as far as i understand works fine for any hic data regardless of the enzyme used. Like Arima, your pipeline only does separate mapping of reads 1 and 2 then filter chimeras (alignments that read through (any) junction to drop the inner-most aligned part of the read that spans the junction) and PCR duplicates.  right?

Thanks!
Fernando

**Comment by esrice** [comment]
Hi Fernando,

That's correct — the enzyme used is only taken into account by SALSA, not by the preprocessing. My new pipeline uses chromap for both alignment and preprocessing, and it does a better job than my implementation of the Arima method (i.e., bwa mem each end separately, filtering chimeric alignments, etc.).

Ed
